package model;

public enum NotificationType {
	MEETING_CANCELLED,
	INVITATION_RECEIVED,
	INVITATION_ACCEPTED,
	INVITATION_REJECTED,
	INVITATION_REVOKED,
	MEETING_TIME_CHANGED,
	MEETING_CHANGE_REJECTED;
}
